version: '3.8'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./src:/src
    ports:
      - "5000:80"

  web:
    build:
      target: build
    volumes:
      - ../web/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_SIGNALR_URL=http://localhost:5000/hubs
    command: npm run dev -- --host
